GET http://localhost:5000/users

##
POST http://localhost:5000/register-user
Content-Type: application/json

{
    "username": "Andrei",
    "password": "password"
}

####

POST http://localhost:5000/login-user
Content-Type: application/json

{
    "username": "Andrei",
    "password": "password"
}
